/*
 *	The MIT License (MIT)
 *
 *	Copyright (c) 2017 Jerry Lee
 *
 *	Permission is hereby granted, free of charge, to any person obtaining a copy
 *	of this software and associated documentation files (the "Software"), to deal
 *	in the Software without restriction, including without limitation the rights
 *	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *	copies of the Software, and to permit persons to whom the Software is
 *	furnished to do so, subject to the following conditions:
 *
 *	The above copyright notice and this permission notice shall be included in all
 *	copies or substantial portions of the Software.
 *
 *	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *	SOFTWARE.
 */

using QuickUnity.Data;

namespace QuickUnity.Data
{
    /// <summary>
    /// TestData
    /// Note: Generated by Editor automatically. Please don't edit this file manually!
    /// </summary>
    public class TestData : DataTableRow
    {
        /// <summary>
        /// ID
        /// </summary>
        public long id;

        /// <summary>
        /// 测试布尔 test bool
        /// </summary>
        public bool testBoolean;

        /// <summary>
        /// test byte
        /// </summary>
        public byte testByte;

        /// <summary>
        /// test sbyte
        /// </summary>
        public sbyte testSByte;

        /// <summary>
        /// test short
        /// </summary>
        public short testShort;

        /// <summary>
        /// test ushort
        /// </summary>
        public ushort testUShort;

        /// <summary>
        /// test int
        /// </summary>
        public int testInt;

        /// <summary>
        /// test uint
        /// </summary>
        public uint testUInt;

        /// <summary>
        /// test ulong
        /// </summary>
        public ulong testULong;

        /// <summary>
        /// test float
        /// </summary>
        public float testFloat;

        /// <summary>
        /// test double
        /// </summary>
        public double testDouble;

        /// <summary>
        /// test decimal
        /// </summary>
        public decimal testDecimal;

        /// <summary>
        /// test string
        /// </summary>
        public string testString;

        /// <summary>
        /// 测试Vector2
        /// </summary>
        public string testVector2;

        /// <summary>
        /// 测试Vector3
        /// </summary>
        public string testVector3;

        /// <summary>
        /// 测试Quaternion
        /// </summary>
        public string testQuaternion;

        /// <summary>
        /// 测试booleanArray
        /// </summary>
        public bool[] testBooleanArray;

        /// <summary>
        /// 测试byteArray
        /// </summary>
        public byte[] testByteArray;

        /// <summary>
        /// 测试sbyteArray
        /// </summary>
        public sbyte[] testSByteArray;

        /// <summary>
        /// 测试shortArray
        /// </summary>
        public short[] testShortArray;

        /// <summary>
        /// 测试ushortArray
        /// </summary>
        public ushort[] testUShortArray;

        /// <summary>
        /// 测试intArray
        /// </summary>
        public int[] testIntArray;

        /// <summary>
        /// 测试uintArray
        /// </summary>
        public uint[] testUIntArray;

        /// <summary>
        /// 测试longArray
        /// </summary>
        public long[] testLongArray;

        /// <summary>
        /// 测试ulongArray
        /// </summary>
        public ulong[] testULongArray;

        /// <summary>
        /// 测试floatArray
        /// </summary>
        public float[] testFloatArray;

        /// <summary>
        /// 测试doubleArray
        /// </summary>
        public double[] testDoubleArray;

        /// <summary>
        /// 测试decimalArray
        /// </summary>
        public decimal[] testDecimalArray;

        /// <summary>
        /// 测试stringArray
        /// </summary>
        public string[] testStringArray;

        /// <summary>
        /// Initializes a new instance of the <see cref="TestData"/> class.
        /// </summary>
        public TestData()
            : base()
        {
        }
    }
}