using QuickUnity.Config;

namespace QuickUnity.Examples.Config.VO
{
    /// <summary>
    /// TestData
	/// Note: Generated by Editor automatically. Please don't edit this file manually !
    /// </summary>
    public sealed class TestData : ConfigMetadata
    {
		/// <summary>
		/// ID
		/// </summary>
		public long id;

		/// <summary>
		/// 测试布尔
		/// test bool
		/// </summary>
		public bool testBool;

		/// <summary>
		/// test byte
		/// </summary>
		public byte testByte;

		/// <summary>
		/// test sbyte
		/// </summary>
		public sbyte testSByte;

		/// <summary>
		/// test short
		/// </summary>
		public short testShort;

		/// <summary>
		/// test ushort
		/// </summary>
		public ushort testUShort;

		/// <summary>
		/// test int
		/// </summary>
		public int testInt;

		/// <summary>
		/// test uint
		/// </summary>
		public uint testUInt;

		/// <summary>
		/// test ulong
		/// </summary>
		public ulong testULong;

		/// <summary>
		/// test float
		/// </summary>
		public float testFloat;

		/// <summary>
		/// test double
		/// </summary>
		public double testDouble;

		/// <summary>
		/// test decimal
		/// </summary>
		public decimal testDecimal;

		/// <summary>
		/// test string
		/// </summary>
		public string testString;

		/// <summary>
		/// 测试boolList
		/// </summary>
		public bool[] testBoolList;

		/// <summary>
		/// 测试byteList
		/// </summary>
		public byte[] testByteList;

		/// <summary>
		/// 测试sbyteList
		/// </summary>
		public sbyte[] testSByteList;

		/// <summary>
		/// 测试shortList
		/// </summary>
		public short[] testShortList;

		/// <summary>
		/// 测试ushortList
		/// </summary>
		public ushort[] testUShortList;

		/// <summary>
		/// 测试intList
		/// </summary>
		public int[] testIntList;

		/// <summary>
		/// 测试uintList
		/// </summary>
		public uint[] testUIntList;

		/// <summary>
		/// 测试longList
		/// </summary>
		public long[] testLongList;

		/// <summary>
		/// 测试ulongList
		/// </summary>
		public ulong[] testULongList;

		/// <summary>
		/// 测试floatList
		/// </summary>
		public float[] testFloatList;

		/// <summary>
		/// 测试doubleList
		/// </summary>
		public double[] testDoubleList;

		/// <summary>
		/// 测试decimalList
		/// </summary>
		public decimal[] testDecimalList;

		/// <summary>
		/// 测试stringList
		/// </summary>
		public string[] testStringList;

		/// <summary>
        /// Initializes a new instance of the <see cref="TestData"/> class.
        /// </summary>
        public TestData()
        {
        }
    }
}