using QuickUnity.Config;

namespace QuickUnity.Examples.Config.VO
{
    /// <summary>
    /// TestDataTwo
	/// Note: Generated by Editor automatically. Please don't edit this file manually !
    /// </summary>
    public sealed class TestDataTwo : ConfigMetadata
    {
		/// <summary>
		/// ID
		/// </summary>
		public long id;

		/// <summary>
		/// 名称
		/// </summary>
		public string itemName;

		/// <summary>
		/// 数值
		/// </summary>
		public float price;

		/// <summary>
        /// Initializes a new instance of the <see cref="TestDataTwo"/> class.
        /// </summary>
        public TestDataTwo()
        {
        }
    }
}